---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neurascale-ops
  namespace: argocd
  labels:
    app.kubernetes.io/name: neurascale-ops
    app.kubernetes.io/part-of: neurascale-platform
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: neurascale-incidents
    notifications.argoproj.io/subscribe.on-health-degraded.slack: neurascale-incidents
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sodiq-code/neurascale-ops.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: neurascale-ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
